### ISSUE TITLE
Cron job for CMS not completing

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#611]
From what I can tell, the cron job for the CMS repo hasn't fully run at least today (I'd need to work through the cron log some more).  It's working fine for all other hosted repos.

Log for the last run of the job:
```sh
[2015-02-04 07:10:01] JTracker.INFO: ---- Bulk Start retrieve Project [] []
[2015-02-04 07:10:01] JTracker.INFO: Processing project: Joomla! CMS [] []
[2015-02-04 07:10:02] JTracker.INFO: Start retrieve Labels [] []
[2015-02-04 07:10:02] JTracker.INFO: Processing project: Joomla! CMS [] []
[2015-02-04 07:10:02] JTracker.INFO: Labels: 0 new, 0 updated, 0 deleted. [] []
[2015-02-04 07:10:02] JTracker.INFO: Finished [] []
[2015-02-04 07:10:02] JTracker.INFO: Start retrieving Milestones [] []
[2015-02-04 07:10:02] JTracker.INFO: Processing project: Joomla! CMS [] []
[2015-02-04 07:10:02] JTracker.INFO: Milestones: 0 new, 7 updated, 0 deleted. [] []
[2015-02-04 07:10:02] JTracker.INFO: Finished [] []
[2015-02-04 07:10:02] JTracker.INFO: Start retrieve Issues [] []
[2015-02-04 07:10:02] JTracker.INFO: Processing project: Joomla! CMS [] []
[2015-02-04 07:10:46] JTracker.INFO: Retrieved 5968 items from GitHub. [] []
```

The next job was the weblinks repo, which had a full run:
```sh
[2015-02-04 07:15:01] JTracker.INFO: ---- Bulk Start retrieve Project [] []
[2015-02-04 07:15:01] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:02] JTracker.INFO: Start retrieve Labels [] []
[2015-02-04 07:15:02] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:02] JTracker.INFO: Labels: 0 new, 0 updated, 0 deleted. [] []
[2015-02-04 07:15:02] JTracker.INFO: Finished [] []
[2015-02-04 07:15:02] JTracker.INFO: Start retrieving Milestones [] []
[2015-02-04 07:15:02] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:02] JTracker.INFO: Milestones: 0 new, 0 updated, 0 deleted. [] []
[2015-02-04 07:15:02] JTracker.INFO: Finished [] []
[2015-02-04 07:15:02] JTracker.INFO: Start retrieve Issues [] []
[2015-02-04 07:15:02] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:03] JTracker.INFO: Retrieved 23 items from GitHub. [] []
[2015-02-04 07:15:04] JTracker.INFO: 0 added, 1 updated. [] []
[2015-02-04 07:15:04] JTracker.INFO: Finished [] []
[2015-02-04 07:15:04] JTracker.INFO: Start retrieve Comments [] []
[2015-02-04 07:15:04] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:04] JTracker.INFO: Getting issue comments. [] []
[2015-02-04 07:15:04] JTracker.INFO: 0 added, 0 updated, 0 deleted. [] []
[2015-02-04 07:15:04] JTracker.INFO: Finished. [] []
[2015-02-04 07:15:04] JTracker.INFO: Start retrieve Events [] []
[2015-02-04 07:15:04] JTracker.INFO: Processing project: Weblinks [] []
[2015-02-04 07:15:04] JTracker.INFO: Added 0 new issue events to the database [] []
[2015-02-04 07:15:04] JTracker.INFO: Finished. [] []
[2015-02-04 07:15:04] JTracker.INFO: Start retrieving Avatars. [] []
[2015-02-04 07:15:04] JTracker.INFO: Processing avatars for 1361 users. [] []
[2015-02-04 07:15:05] JTracker.INFO: Added 0 new user avatars [] []
[2015-02-04 07:15:05] JTracker.INFO: Finished. [] []
[2015-02-04 07:15:05] JTracker.INFO: ---- Bulk Finished [] []
```

**Comment by mbabker** [comment]
The repo is eating up the entire API limit in one run.

```sh
------------------------------------------------------------
              Joomla! Tracker CLI Application
                         1.0.0-beta
------------------------------------------------------------
------------------------------------------------------------
                      Retrieve Project
------------------------------------------------------------

GitHub rate limit:... 5000 (remaining: 4020)

Updating project info for project: joomla/joomla-cms
------------------------------------------------------------
                      Retrieve Labels
------------------------------------------------------------
Fetching labels...ok

------------------------------------------------------------
                    Retrieve Milestones
------------------------------------------------------------
Fetching milestones...ok

------------------------------------------------------------
                      Retrieve Issues
------------------------------------------------------------
Retrieving open items from GitHub...(100)(100)(100)(100)(100)(12)
Retrieving closed items from GitHub...(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(100)(76)
Adding issues to the database...
[=======================> ] 5843/5988 15:52.72 ETA: 00:55.47

ERROR: API rate limit exceeded for jissues-bot.

Call stack:
#0 JPATH_ROOT/cli/Application/Command/Get/Project/Issues.php(303): Joomla\Github\Package\Pulls->get('joomla', 'joomla-cms', 5843)
#1 JPATH_ROOT/cli/Application/Command/Get/Project/Issues.php(87): Application\Command\Get\Project\Issues->processData()
#2 JPATH_ROOT/cli/Application/Command/Get/Project.php(211): Application\Command\Get\Project\Issues->execute()
#3 JPATH_ROOT/cli/Application/Command/Get/Project.php(132): Application\Command\Get\Project->processIssues()
#4 JPATH_ROOT/cli/Application/Application.php(249): Application\Command\Get\Project->execute()
#5 JPATH_ROOT/vendor/joomla/application/src/AbstractApplication.php(105): Application\Application->doExecute()
#6 JPATH_ROOT/cli/tracker.php(40): Joomla\Application\AbstractApplication->execute()
```
