### ISSUE TITLE
Non Coloborator are unable to edit issues

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#868]
### Steps to reproduce the issue

login with an account that is not allowed to commit or edit the issues. try to do that as member of the JBS Group.

#### Expected result

state and or description etc. changes. via the bot account

#### Actual result

```
403 RuntimeException
Invalid response from GitHub

exception: exception 'JTracker\Github\Exception\GithubException' with message 'Issue not editable by zero-24' in ROOT/src/JTracker/Github/GithubObject.php:49
Stack trace:
#0 ROOT/src/JTracker/Github/Package/Issues.php(155): JTracker\GitHub\GithubObject->processResponse(Object(Joomla\Http\Response))
#1 ROOT/src/App/Tracker/Controller/Issue/Save.php(357): JTracker\Github\Package\Issues->edit('joomla', 'joomla-cms', '11672', 'closed', 'Bundled FOF 2.4...', '### Steps to re...', NULL, NULL, Array)
#2 ROOT/src/App/Tracker/Controller/Issue/Save.php(152): App\Tracker\Controller\Issue\Save->updateGitHub('11672', Array, 'closed', 'open', NULL, NULL, Array)
#3 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#4 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#5 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#6 {main}

Next exception 'RuntimeException' with message 'Invalid response from GitHub' in ROOT/src/App/Tracker/Controller/Issue/Save.php:173
Stack trace:
#0 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#3 {main}
```

**Comment by mbabker** [comment]
My initial guess, something changed along the way with response codes.

https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L420

**Comment by zero-24** [comment]
hmm looks like they moved it to 403? Maybe we double check for 404 & 403?

**Comment by zero-24** [comment]
hmm looks like now we have the wrong commenter.

see: https://github.com/joomla/joomla-cms/issues/11682#issuecomment-241201003

I would expect the this comment is done by @joomla-cms-bot

**Comment by zero-24** [comment]
Works now thanks @mbabker
