### ISSUE TITLE
PR causes  422 RuntimeException  Invalid response from GitHub

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/jissues#955]
Saving Issue #13027 gives `422 RuntimeException  Invalid response from GitHub`, Issue isn't saved.

**Comment by b2z** [comment]
Confirmed. Interesting that on my local instance trying to edit/save 13027 I have another error
```
403 RuntimeException

Invalid response from GitHub

exception: JTracker\Github\Exception\GithubException: Issue not editable by b2z in ROOT/src/JTracker/Github/GithubObject.php:49
Stack trace:
#0 ROOT/src/JTracker/Github/Package/Issues.php(145): JTracker\GitHub\GithubObject->processResponse(Object(Joomla\Http\Response))
#1 ROOT/src/App/Tracker/Controller/Issue/Save.php(356): JTracker\Github\Package\Issues->edit('joomla', 'joomla-cms', 13027, 'open', '[4.0] com_conte...', 'Pull Request fo...', NULL, NULL, Array)
#2 ROOT/src/App/Tracker/Controller/Issue/Save.php(155): App\Tracker\Controller\Issue\Save->updateGitHub(13027, Array, 'open', 'open', NULL, NULL, Array)
#3 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#4 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#5 ROOT/www/index.php(106): Joomla\Application\AbstractWebApplication->execute()
#6 ROOT/www/index.php(133): {closure}()
#7 {main}```

**Comment by zero-24** [comment]
@b2z do you test against the CMS Repo?

Than the error makes sense as you don't have access to the CMS Repo using github.

`exception: JTracker\Github\Exception\GithubException: Issue not editable by b2z in ROOT/src/JTracker/Github/GithubObject.php:49`

**Comment by mbabker** [comment]
That shouldn't be blocking his tests though because that Exception should be caught and trigger a bot trying to perform the action on his behalf.

**Comment by zero-24** [comment]
Yes but if i have understand @b2z he is esting on his own repo against the cms

**Comment by b2z** [comment]
Yeap I ma trying to edit :)
