### ISSUE TITLE
Can't install repo mysql :(

### ISSUE THREAD

**Issue by wilsonge** [joomla/jissues#981]
#### Steps to reproduce the issue
```
george@ ~/Sites/jissues (master) $ bin/jtracker install
------------------------------------------------------------
              Joomla! Tracker CLI Application
                         1.0.0-beta
------------------------------------------------------------
------------------------------------------------------------
                         Installer
------------------------------------------------------------

WARNING: A database has been found!

Do you want to reinstall?

1) Yes
2) No

Select:1
Removing existing tables...ok
Creating tables from file /Users/george/Sites/jissues/etc/mysql.sql.

ERROR: Field 'gh_editbot_user' doesn't have a default value

Call stack:
#0 JPATH_ROOT/cli/Application/Command/Install/Install.php(200): Joomla\Database\Mysqli\MysqliDriver->execute()
#1 JPATH_ROOT/cli/Application/Command/Install/Install.php(116): Application\Command\Install\Install->processSql()
#2 JPATH_ROOT/cli/Application/Application.php(214): Application\Command\Install\Install->execute()
#3 JPATH_ROOT/vendor/joomla/application/src/AbstractApplication.php(109): Application\Application->doExecute()
#4 JPATH_ROOT/cli/tracker.php(125): Joomla\Application\AbstractApplication->execute()
#5 JPATH_ROOT/cli/tracker.php(151): {closure}()
#6 {main}george@ ~/Sites/jissues (master) $ 

george@ ~/Sites/jissues (master) $ mysql --version
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for osx10.12 (x86_64) using readline 5.1
george@ ~/Sites/jissues (master) $ php --version
PHP 7.1.7 (cli) (built: Jul 19 2017 15:58:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

#### Expected result
I can install the repo locally :)

#### Actual result
I can't

#### System information (as much as possible)
See stack

**Comment by wilsonge** [comment]
OK Well I guess I went here before. Closing in favour of my newer issue #1006
